public class PostOfficeBranch {
    public string Name{get;set;}
    public string Description{get;set;}
    Public string BranchType{get;set;}
    Public string DeliveryStatus{get;set;}
    Public string Circle{get;set;}
    Public string District{get;set;}
    Public string Division{get;set;}
    Public string Region{get;set;}
    Public string State{get;set;}
    Public string Country{get;set;}
}